services:
  mysql:
    image: mysql:latest
    container_name: chatbot_db
    restart: always
    ports:
      - "3313:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: bot
      MYSQL_USER: Jimmy
      MYSQL_PASSWORD: 12345